localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/ar.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/da.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/de.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/el.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/es.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/fil.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/fr.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/it.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/ja.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/ko.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/kk.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/nl.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/pl.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/pt-BR.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/ru.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/sv.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/th.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/tr.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/uk.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/ur.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/vi.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/zh-CN.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/zh-Hans.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/zh-HK.lproj/Localizable.strings -r
localisort -t ./Application/GreenSn0w/en.lproj/Localizable.strings -i ./Application/GreenSn0w/zh-TW.lproj/Localizable.strings -r
